.MODEL SMALL

.STACK 100h

.DATA
MSG1 DB 'Digite um caractere: $'
NUM1 DB 10,13,'O caractere digitado e um numero.$'
LETRA1 DB 10,13,'O caractere digitado e uma letra.$'
DESCONHECIDO1 DB 10,13,'O caractere digitado e desconhecido.$'

.CODE
MAIN PROC

MOV AX,@DATA
MOV DS,AX

;EXIBE A MSG1

MOV AH,9
MOV DX, OFFSET MSG1
INT 21h

;RECEBE O CARACTERE

MOV AH,1
INT 21h

;COPIA PARA BL
MOV BL, AL

CMP BL, 47 ;SE FOR MAIOR QUE 47 
JA PODESERNUM 

JMP DESCONHECIDO

PODESERNUM:
    CMP BL, 58 ; E MENOR QUE 58 Eh NUMERO
    JB NUM

    CMP BL, 64
    JA PODESERLETRA ;SE FOR MAIOR PODE SER LETRA

    JMP DESCONHECIDO


PODESERLETRA:
    CMP BL, 91 ;SE FOR ENTRE 64 E 91 E LETRA MAIUSCULA
    JB LETRA

    CMP BL, 91
    JAE PODESERLETRA2 ;SE FOR MAIOR OU IGUAL QUE 91 IRA VERIFICAR SE NAO E LETRA OU SE E LETRA MINUSCULA


PODESERLETRA2:
    CMP BL, 96
    JBE DESCONHECIDO; SE NAO ESTIVER ENTRE 96 E 122 E DESCONHECIDO E SE ESTIVER E UMA LETRA

    CMP BL,122
    JA DESCONHECIDO

    JMP LETRA


LETRA: ;SE FOR LETRA EXIBE A MENSAGEM FALANDO QUE E LETRA
MOV AH,9
MOV DX,OFFSET LETRA1
INT 21h
JMP FIM

NUM:;SE FOR NUM EXIBE A MENSAGEM FALANDO QUE E NUM
MOV AH,9
MOV DX,OFFSET NUM1
INT 21h
JMP FIM

DESCONHECIDO:;SE FOR DESCONHECIDO EXIBE A MENSAGEM FALANDO QUE E DESCONHECIDO
MOV AH,9
MOV DX,OFFSET DESCONHECIDO1
INT 21h
JMP FIM

FIM:
; FINALIZA O PROGRAMA
MOV AH,4Ch
INT 21h

MAIN ENDP
END MAIN