.MODEL SMALL
.STACK 100H
.DATA
 MSG DB 'DIGITE UM NUMERO BINARIO (MAX 16 BITS): $'
.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX

    LEA DX, MSG; EXIBE MENSAGEM
    MOV AH, 9
    INT 21H

    XOR BX, BX ; LIMPA BX
    MOV AH, 1

WILE:
    INT 21H ; LE O NUMERO INSERIDO
    CMP AL, 13
    JE DEF_FUNCAO; SE O NUMERO INSERIDO FOR O CR(13) ELE PULA
    CMP AL, '0'       
    JE ZERO
    SHL BX, 1     ; DESLOCA BX 1 CASA PARA A ESQUERDA
    OR BX, 1    ; INSERE 1 NO LSB
    JMP WILE  ; VOLTA PARA RECEBER MAIS CARACTERES

ZERO:
    SHL BX, 1    ; DESLOCA BX 1 CASA PARA A ESQUERDA E ADICIONA 0 EM LSB
    JMP WILE    ; VOLTA PARA RECEBER MAIS CARACTERES

DEF_FUNCAO:
    MOV AH, 02h        ; FUNÇÃO PARA IMPRIMIR CARACTERE
    MOV CX, 16 ; DEFINE O CONTADOR COMO 16

IMPRIME_LOOP:
    ROL BX, 1          ; DESLOCA BX 1 CASA PARA A ESQUERDA
    JC UM_CARRY        ; VERIFICA SE O CARRY É 1, SE FOR PULA PARA IMPRIMIR UM
    MOV DL, '0'         ;SE NAO IMPRIME ZERO
    JMP IMPRIME

UM_CARRY:
    MOV DL, '1'

IMPRIME:
    INT 21H            ; IMPRIME O CARACTERE
    LOOP IMPRIME_LOOP  ; REPETE PARA O PRÓXIMO BIT

    MOV AH, 4CH
    INT 21H

MAIN ENDP
END MAIN
